name: build.yml

on: [push, pull_request]

env:
  plugin: Robotone

jobs:

  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - if: matrix.os == 'macos-latest'
        name: Setup (MacOS)
        run: ./scripts/prebuild_macos.sh

      - if: matrix.os == 'ubuntu-latest'
        name: Setup (Ubuntu)
        run: ./scripts/prebuild_ubuntu.sh

      - if: matrix.os == 'windows-latest'
        name: Setup (Windows)
        run: .\scripts\prebuild_windows.bat
        shell: cmd

      - if: matrix.os == 'macos-latest'
        name: Build (MacOS)
        run: ./scripts/build_macos.sh

      - if: matrix.os == 'ubuntu-latest'
        name: Build (Ubuntu)
        run: ./scripts/build_ubuntu.sh

      - if: matrix.os == 'windows-latest'
        name: Build (Windows)
        run: .\scripts\build_windows.bat
        shell: cmd

      - if: matrix.os == 'macos-latest'
        name: Test (MacOS)
        run: ./scripts/postbuild_macos.sh

      - if: matrix.os == 'ubuntu-latest'
        name: Test (Ubuntu)
        run: ./scripts/postbuild_ubuntu.sh

      - if: matrix.os == 'windows-latest'
        name: Test (Windows)
        run: .\scripts\postbuild_windows.bat
        shell: cmd

      - if: github.event_name == 'push'
        name: Upload build artefacts
        uses: actions/upload-artifact@master
        with:
          name: ${{env.plugin}}-${{matrix.os}}
          path: ./build/src/${{env.plugin}}/${{env.plugin}}_artefacts/Release

  release:
    if: github.ref_type == 'tag'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all build artefacts
        uses: actions/download-artifact@master
        with:
          path: ./artefacts

      - name: Upload all artefacts to GitHub release
        uses: softprops/action-gh-release@master
        with:
          files: ./artefacts/*
